### ISSUE TITLE
janus_track and janus_association

### ISSUE THREAD

**Issue by stephenrawls** [Noblis/INVSC-janus#27]
Hi,

I have a question about the intended use of `janus_track` and `janus_association` objects.

From skimming over the API, it looks like:
1) A call to `janus_detect()` outputs a vector of `janus_track` objects, essentially one `janus_track` object per detected subject. Each of the `janus_track` objects are themselves vectors of `janus_attributes` structures, essentially one `janus_attributes` object per frame in which the subject was detected.

2) A `janus_association` object contains a reference to a media object, along with a vector of `janus_track` objects. The comment on `janus_association` says that each of the `janus_track` objects refers to the same subject.

It's unclear to me why a `janus_association` object isn't just a struct containing a reference to a media object along with a single `janus_track` object. That single `janus_track` object  would contain a vector of `janus_attributes` objects, one for each frame in the associated media that the subject appears in.

Can you explain the intended use of these objects, and what do different `janus_track` entries inside a single `janus_association` object represent?

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

Multiple `janus_track`s inside a single association were intended to represent a tracking scenario where a performer found two distinct tracks of a single subject in one video. Looking through the API after your comment though I realized this use case is impossible. A `janus_association` is now only used to represent a piece of media and it's groundtruth metadata which will never have multiple tracks. I think that the struct can be refactored to only have a single track now. Thanks!

**Comment by JordanCheney** [comment]
janus_association has been updated in commit cfe4cc89208d7084989534a3f47b5dfa59dec92b.
