### ISSUE TITLE
Question about videos in janus_media

### ISSUE THREAD

**Issue by stephenrawls** [Noblis/INVSC-janus#29]
Hi,

I was looking at the `janus_media` object, and had a concern that it could cause memory issues. Here is the definition of `janus_media` from iarpa_janus.h:

```
typedef struct janus_media
{
    std::vector<janus_data*> data; /*! < \brief A collection of image data of size N,
                                                where is the number of frames in a video
                                                or 1 in the case of a still image. */
    size_t width;     /*!< \brief Column count in pixels. */
    size_t height;    /*!< \brief Row count in pixels. */
    size_t step;      /*!< \brief Bytes per frame, including padding. */
    janus_color_space color_space; /*!< \brief Arrangement of #data. */
} janus_media;
```

As you can see, it represents a video as a vector of frames, completely uncompressed. That is, the total required memory for a single video is: `w*h*nChannels*nFrames`. Furthermore, when constructing templates, the API forces all videos for a template to be loaded into memory simultaneously.

It seems that if a lot of videos were processed then memory would quickly become an issue. Especially considering that clients are probably trying to create multiple templates in parallel on the same machine.

To put a hard-number on it, take the following video file from CS2: `CS2/video_clips/35756.mp4`. It has 720 frames, and each frome is 1280x720 pixels. So the amount of memory it requires to load fully uncompressed into memory is `1280*720*3/10^9 = 2.07 GB`. It only takes a couple video files like that per subject to really start constraining how many templates you can process in parallel on a single machine, with memory likely to be the bottleneck before CPU or GPU compute resources are exhausted.

It might not be an issue for the evaluation (e.g. NIST has machines with a heck of a lot of RAM), but it seems like a usability issue for future government users.

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

You're right that this method will use a considerable amount of memory, especially with HD video. Our hope was that providing all of the data at one time would lead to optimization opportunities for performers who could, for example, copy more data to the GPU in a single batch. If other people think that memory will be an issue I'm open to storing the video data in a more optimized fashion. Tomorrow, I will also look through the CS3 metadata and see what the maximum memory requirement for a single template is. That might give us a good indication as to how much of a bottleneck this will be.

**Comment by stephenrawls** [comment]
Hi Jordan,

You're correct that it is good to have all the media at one time to allow for batch processing.  For videos, perhaps just pass us the file paths and allow us to handle choosing when to load them into memory, and how many frames to process/keep around?

Or alternatively just leave things as they are for the evaluation--but note that this has the possibility of biting end-users if this API ever leaks out to real-world govt. customers.

Did you ever determine what the max size for a single template is?

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

I finally had a chance to query the CS3 videos for the largest memory footprint. Video `21490.mp4` is a 9 minute 50 second clip at 25 FPS and 960x720x3 resolution which gives a total size of about 28 GB (assuming unsigned 8 bit color channel values). We have machines on the evaluation side that can handle this kind of load but I'm curious if this will be a large burden on you or the other performers (constrains you to only run on your larger machine etc). I certainly don't want the API to limit your ability to test and iterate quickly. I'm open to suggestions on a more efficient way to handle large video files, perhaps passing in the file paths is a better solution.

Best,
Jordan

**Comment by stephenrawls** [comment]
Hi Jordan,

I can't speak for the other performers, but from our perspective we have machines with plenty of RAM, so it's not a limiting factor for us.

Again--as long as this API is only meant for research evaluation, this probably isn't a problem. My concern is that if this API leaks out to a real-world govt. customer, that this would be a pretty big limiting factor for them, if they have lots of video data.

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

This version of the API is confirmed to be evaluation-only. We will need to revisit this issue as we move forward but for now I am not going to make any changes.
