### ISSUE TITLE
Using Gallery to Improve Model

### ISSUE THREAD

**Issue by stephenrawls** [Noblis/INVSC-janus#31]
Hi,

One thing that many Janus teams are doing is using the gallery to improve their face recognition models. (e.g. training some type of model adaptation or unsupervised dimensionality reduction using gallery data).

In the Phase 1 API this was done in the "janus_flatten_gallery()" function call. There is no corresponding function call in the current API.

It seems to me it would be useful to have a `janus_prepare_gallery()` function call that would be optional. If an implementation makes use of the gallery data in any way, they can have a check in their `janus_search()` implementations to determine if the gallery has been prepared or not prior to beginning the search, and prepare it if necessary.

The purpose of having an explicit (optional) `janus_prepare_gallery()` function is for clients to call it when they know they are done adding things to the gallery, and perform the required operations at that time as opposed to the time of the first search, where an end-user might be surprised that some searches take a much longer amount of time than normal.

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
Hi Stephen,

The intention was any gallery training could be done during `janus_create_gallery()`. Because the function gets all of the templates to be enrolled as input we assumed that this was sufficient information for training. Please let me know if that is not the case.

**Comment by stephenrawls** [comment]
Hi Jordan,

The presence of `janus_gallery_insert()` and `janus_gallery_remove()` means that clients can modify the gallery after the initial `janus_create_gallery()` call. So if a user adds 100 new subjects via iteratively calling `janus_gallery_insert()`, then we would probably want to update our model (but not pay the price to update it 100 successive times).

**Comment by JordanCheney** [comment]
Hi Stephen,

I see what you're saying. So a function `janus_prepare_gallery(janus_gallery gallery)` would be useful? Would your preference be to check in `janus_search` if the gallery needs to be prepared or to require it in the test harness? My preference would be to have it be called directly from the harness so that we can separate the time it takes to do search and the time it takes to do gallery training.

**Comment by stephenrawls** [comment]
Hi Jordan,

Yes, given the ability to modify the gallery after initial gallery creation, it would be useful to have a function to prepare the gallery.

I don't have a strong preference on weather or not to require the gallery to be prepared. From an implemntation point of view, we can easily handle checking to see if the client prepared the gallery prior to doing a search, and prepare it if nescesary. So if we want to be lenient then we make it optional. But on the other hand, if we want to avoid causing undue surpises to the user, e.g. some searches taking a very long time due to the need to prepare the gallery prior to actually doing the search, then we would throw an error if the user tried calling `janus_search()` without first preparing the gallery.

Thanks,
Stephen Rawls (ISI)

**Comment by JordanCheney** [comment]
`janus_prepare_gallery` has been added in dd67018f606a207a9b3abe9f3e0653c3a22d61cf
