### ISSUE TITLE
Tracking in videos

### ISSUE THREAD

**Issue by nxwhite-str** [Noblis/INVSC-janus#34]
Tracking subjects in videos will have the best performance when all frames of a video are available for detection and tracking.  I believe it has been stated previously the intent was for the test harness to pass all frames for video media to janus_detect (and the second versions of janus_create_template and janus_cluster), rather than just the key frames as was done for Phase I.

Is that correct? If so, I would suggest updating the documentation for janus_media to make this part of the API contract.

**Comment by JordanCheney** [comment]
You are correct that all video frames (not just key frames) will be given to the algorithms to facilitate more robust tracking. This is somewhat related to issue #29 that the ISI team raised about the large amount of memory an uncompressed full video can use. As of now, I don't have a good solution for the RAM issue and I am open to suggestions. I will update the documentation to make this more clear
