### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by carlosdcastillo** [Noblis/INVSC-janus#39]
I think you are leaking one complete media each time you go through this iteration, which in an entire detection run will leak about 77K images or > 200GB

https://github.com/biometrics/janus/blob/phase2/src/janus_io.cpp#L123-L160

**Comment by JordanCheney** [comment]
Hey Carlos,

You're correct. I will have a fix for this soon.

Thanks!
Jordan

**Comment by JordanCheney** [comment]
Hi Carlos,

This was fixed a while ago but I forgot to close this issue. Please see PR #40 for details.
